src/Entity/AnimaProgram.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnimaProgramRepository")
 */
class AnimaProgram
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $program_id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $program_name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProgramId(): ?int
    {
        return $this->program_id;
    }

    public function setProgramId(int $program_id): self
    {
        $this->program_id = $program_id;

        return $this;
    }

    public function getProgramName(): ?string
    {
        return $this->program_name;
    }

    public function setProgramName(string $program_name): self
    {
        $this->program_name = $program_name;

        return $this;
    }
}

src/Form/AnimaProgramType.php
<?php

namespace App\Form;

use App\Entity\AnimaProgram;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnimaProgramType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('program_id')
            ->add('program_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AnimaProgram::class,
        ]);
    }
}

src/Controller/AnimaProgramController.php
<?php

namespace App\Controller;

use App\Entity\AnimaProgram;
use App\Form\AnimaProgramType;
use App\Repository\AnimaProgramRepository;
use App\Repository\AnimeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Psr\Log\LoggerInterface;

/**
 * @Route("/anima/program")
 */
class AnimaProgramController extends AbstractController
{
    // logger
    private $logger;
    public function __construct(LoggerInterface $logger){
        $this->logger = $logger;
    }

    /**
     * @Route("/anima", name="anima_program_index", methods={"GET"})
     */
    public function index(AnimaProgramRepository $animaProgramRepository,AnimeRepository $animeRepository): Response
    {
        /*
            $animaprograms = $this->getDoctrine()
            ->getRepository('App\Entity\Article')
            ->findAll();
            summer spring fall winter
        */

        $animes = $animeRepository->findBy(['season'=>'winter'],null,20);
        $list = [];
        foreach($animes as $anime){
            
            $list[] = [
                'title' => $anime->getTitle(),
                'image' => $anime->getImage(),
                'description_low' => substr($anime->getDescription(),0,100),
                'score' => $anime->getScore(),
            ];
        }

        return $this->render('anima_program/index.html.twig', [
            'anima_programs' => $animaProgramRepository->findAll(),
            'animas' => $list
        ]);
    }

    /**
     * @Route("/anima/new", name="anima_program_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $animaProgram = new AnimaProgram();
        $form = $this->createForm(AnimaProgramType::class, $animaProgram);
        $form->handleRequest($request);

        /*
            $article = $form->getData();
        */

        if ($form->isSubmitted()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($animaProgram);
            $entityManager->flush();

            return $this->redirectToRoute('anima_program_index');
        }

        return $this->render('anima_program/new.html.twig', [
            'anima_program' => $animaProgram,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/anima/{id}", name="anima_program_show", methods={"GET"})
     */
    public function show(AnimaProgram $animaProgram): Response
    {
        return $this->render('anima_program/show.html.twig', [
            'anima_program' => $animaProgram,
        ]);
    }

    /**
     * @Route("/anima/{id}/edit", name="anima_program_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, AnimaProgram $animaProgram): Response
    {

        $form = $this->createForm(AnimaProgramType::class, $animaProgram);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('anima_program_index');
        }

        return $this->render('anima_program/edit.html.twig', [
            'anima_program' => $animaProgram,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/anima/{id}", name="anima_program_delete", methods={"DELETE"})
     */
    public function delete(Request $request, AnimaProgram $animaProgram): Response
    {

        $em = $this->getDoctrine()->getManager();
        $program = $em->getRepository('App\Entity\AnimaProgram')->find($animaProgram->getId());

        if (!$program) {
            throw $this->createNotFoundException(
                'ops, nao encontrado: '
            );
        }

        $em->remove($program/* $animaProgram */);
        $em->flush();

        return $this->redirectToRoute('anima_program_index');
    }
}

templates/anima_program/_delete_form.html.twig
<form method="post" action="{{ path('anima_program_delete', {'id': anima_program.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ anima_program.id) }}">
    <button class="btn">Delete</button>
</form>

templates/anima_program/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/anima_program/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit AnimaProgram{% endblock %}

{% block body %}
    <h1>Edit AnimaProgram</h1>

    {{ include('anima_program/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('anima_program_index') }}">back to list</a>

    {{ include('anima_program/_delete_form.html.twig') }}
{% endblock %}

templates/anima_program/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}AnimaProgram index{% endblock %}

{% block body %}
    <h1>AnimaProgram index</h1>

    <div class="row">
        {% for anima_program in anima_programs %}
            <div class="col-sm-3">
                <div class="card text-white bg-dark mb-3">
                    <div class="card-header">
                        <div class="card-title">
                            {{ anima_program.id }} - {{ anima_program.programName }}
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="btn-group">
                            <a class="btn btn-outline-info fa fa-eye " href="{{ path('anima_program_show', {'id': anima_program.id}) }}"> show</a>
                            <a class="btn btn-outline-warning fa fa-pencil" href="{{ path('anima_program_edit', {'id': anima_program.id}) }}"> edit</a>
                        </div>
                    </div>

                </div>
            </div>
        {% else %}
            ops, nada encontrado
        {% endfor %}

        <section>
            <div class="container my-5 py-3">
                <div class="row">
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae asperiores pariatur dignissimos itaque necessitatibus nam minus laudantium porro inventore cum ullam nisi, veniam, fugit deleniti explicabo nemo accusamus. Alias distinctio quisquam
                    </p>
                </div>
            </div>
        </section>
        <section class="main-content">
            <div class="container">
                <div class="row py-5 position-relative">
                    <div class="col-sm-12 col-md-3">
                        <div class="subheading-wrapper mb-2">
                            <span class="subheading">Lorem ipsum dolor.</span>
                        </div>
                        <div class="heading-wrapper mb-2">
                            <span class="heading">
                            Lorem ipsum dolor sit.
                            </span>
                        </div>
                        <div class="content-wrapper">
                            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptas, magnam facere inventore culpa suscipit ducimus exercitationem doloremque mollitia quod voluptate ipsa dolorem enim sint eaque quos debitis sapiente ipsam architecto velit sed!</p>
                        </div>
                    </div>
                    <div class="col-md-9 col-sm-12">
                        <div class="row position-absolute floating-wrapper slider owl-carousel owl-theme d-flex">
                            {% for anima in animas %}
                            <!--<div class="col-6 col-lg-3">-->
                            <!-- card anima -->
                            <div class="card text-white bg-dark mb-3 flex-fill home-card">
                                <img style="object-fit: cover;" class="card-img-top" height="200px" src="{{anima.image}}">
                                <div class="card-body">
                                    <div class="card-title">
                                        {{ anima.title }} - {{ anima.score }}
                                    </div>
                                    <div class="card-text">
                                        {{ anima.description_low }}
                                    </div>
                                </div>
                            </div>
                            <!--</div>-->
                            {% else %}
                                ops, nada encontrado
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>

    <a class="" href="{{ path('anima_program_new') }}">Create new</a>
{% endblock %}

{% block javascripts %}
    <script>
        $('.owl-carousel').owlCarousel({
          loop: true,
          margin: 10,
          nav: true,
          responsive: {
            0: {
              items: 3
            },
            600: {
              items: 3
            },
            1000: {
              items: 3
            }
          }
        });
    </script>
{% endblock %}

templates/anima_program/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New AnimaProgram{% endblock %}

{% block body %}
    <h1>Create new AnimaProgram</h1>

    <!--{{ include('anima_program/_form.html.twig') }}-->

    <form name="anima_program" method="post">
	    <!--<div id="anima_program">-->
        <div class="form-group">
        	<label for="anima_program_program_id" class="required">Program id</label>
        	<input class="form-control" type="number" id="anima_program_program_id" name="anima_program[program_id]" required="required">
        </div>

        <div  class="form-group">
        	<label for="anima_program_program_name" class="required">Program name</label>
        	<input class="form-control" type="text" id="anima_program_program_name" name="anima_program[program_name]" required="required" maxlength="150">
        </div>

        <!--<input type="hidden" id="anima_program__token" name="anima_program[_token]" value="8K1YY3YQJhXvjPqZE92dLiWBugNvx_ZxQda1v1rXxlI">-->
	    <!--</div>-->
	    <button class="btn btn-success">Save</button>
	</form>

    <a href="{{ path('anima_program_index') }}">back to list</a>
{% endblock %}

templates/anima_program/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}AnimaProgram{% endblock %}

{% block body %}
    <h1>AnimaProgram</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ anima_program.id }}</td>
            </tr>
            <tr>
                <th>Program_id</th>
                <td>{{ anima_program.programId }}</td>
            </tr>
            <tr>
                <th>Program_name</th>
                <td>{{ anima_program.programName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('anima_program_index') }}">back to list</a>

    <a href="{{ path('anima_program_edit', {'id': anima_program.id}) }}">edit</a>

    {{ include('anima_program/_delete_form.html.twig') }}
{% endblock %}